# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Test
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: job1
    displayName: job1
    steps:
    - task: Bash@3
      displayName: A
      inputs:
        targetType: 'filePath'
        script: |
          echo "checking dateAAAA"
    - task: Bash@3
      displayName: B
      inputs:
        targetType: 'filePath'
        script: |
          echo "checking dateBBBB"

#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
