spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=test;loginTimeout=30;socketTimeout=30000
    username: sa
    password: passWord567
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leakDetectionThreshold: 100000
      connectionTimeout: 100000
      maximumPoolSize: 5
      minimumIdle: 10
      connectionTestQuery: SELECT 1
      connectionInitSql: SET XACT_ABORT ON
    jmx:
      enabled: true
    jpa:
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          globally-quoted_indentifiers: true
          dialect: org.hibernate.spatial.dialect.sqlserver.SqlServer2008SpatialDialect
    output.ansi.enabled: always

    flyway:
      baselineVersion: 0.0.0
      baseline-on-migrate: true